var APIKey = 'a5d505e479bd3031d6a59512b8809b6bf1bb23f7ebfc61bd3';

//API call to get the random adjective
var API_Endpoint_Word = 'http://api.wordnik.com/v4/words.json/randomWord?hasDictionaryDef=true&includePartOfSpeech=adjective&minCorpusCount=0&maxCorpusCount=-1&minDictionaryCount=1&maxDictionaryCount=-1&minLength=4&maxLength=7&api_key=a2a73e7b926c924fad7001ca3111acd55af2ffabf50eb4ae5'

var API_Endpoint_Word_Two = 'http://api.wordnik.com:80/v4/words.json/randomWord?hasDictionaryDef=true&includePartOfSpeech=noun&minCorpusCount=0&maxCorpusCount=-1&minDictionaryCount=1&maxDictionaryCount=-1&minLength=3&maxLength=6&api_key=a2a73e7b926c924fad7001ca3111acd55af2ffabf50eb4ae5'

//what is returned by the API for the first word
var wordOne;

//what is returned by the API for the second word
var wordTwo; 

//what is returned by the API for the definition of wordOne
var defOne = [];

var defTwo = [];

//array of cover images
var coverArray = new Array('<img src="images/cover.jpg">', '<img src="images/coverTwo.jpg">', '<img src="images/coverThree.png">', '<img src="images/coverFour.png">', '<img src="images/coverFive.png">');

//loads the definition of wordOne on the DOM ***THIS IS WHERE THERE ARE FUCKING PROBLEMS***
var loadDef = function(response){
  //if there is an error, stop the function
  // if(response.error){
  //   return;
  // };

  // //attempt to pick out part of the result data from the array of results returned by the API
  // for(i = 0; i < 2; i++){
    defOne = response;
    console.log(defOne);
    //displays defOne in the div with an ID of "#defOne"
    $('#defOne').text(defOne);
  // }
  // console.log(response.text);
};

var loadDefTwo = function(response){
  defTwo = response;
  console.log(defTwo);
  //displays defTwo in teh div with an ID of "#defTwo"
  $('#defTwo').text(defTwo);
};

//calls the API to get the definition of wordOne
var getDef = function(response) {
  //API endpoint to get the definition of wordOne —— DIFFERENT URL than the get for the random word 
  var API_Endpoint_Def = 'http://api.wordnik.com:80/v4/word.json/' + wordOne + '/definitions?limit=1&includeRelated=false&sourceDictionaries=all&useCanonical=false&includeTags=false&api_key=a2a73e7b926c924fad7001ca3111acd55af2ffabf50eb4ae5'
  //calls the API
  API_Endpoint_Def.replace(wordOne, response.word);
  console.log(API_Endpoint_Def);
  $.ajax({
    url : API_Endpoint_Def,
    dataType : 'jsonp',
    success : function(response){
      console.log(response);
      //calls the loadDef function to load the response into the DOM
      loadDef();
    }

  });
};

var getDefTwo = function(response) {
  //API endpoint to get the defintion of wordTwo
  var API_Endpoint_Def_Two = 'http://api.wordnik.com:80/v4/word.json/' + wordTwo + '/definitions?limit=1&includeRelated=false&sourceDictionaries=all&useCanonical=false&includeTags=false&api_key=a2a73e7b926c924fad7001ca3111acd55af2ffabf50eb4ae5'
  //calls the API
  API_Endpoint_Def_Two.replace(wordTwo, response.word);
  console.log(API_Endpoint_Def_Two);
  $.ajax({
    url : API_Endpoint_Def_Two,
    dataType : 'jsonp',
    success : function(response){
      console.log(response);
      //calls the loadDef function to load the response into the DOM
      loadDefTwo();
    }

  });
};

//loads wordOne on the DOM
var loadWord = function(response){
  //if there is an error, stop the function
  if(response.error){
    return;
  };

  //wordOne is the word contents of the response generated by the API
  wordOne = response.word;
  //displays wordOne in the div with an ID of "#wordOne"
  $('#wordOne').text(wordOne);

};

//loads wordTwo on the DOM
var loadWordTwo = function(response){
  //if there is an error, stop the function
    if(response.error){
      return;
    };

  //wordTwo is the word contents of the response generated by the API
  wordTwo = response.word;
  //displays wordTwo in teh div with an ID of "#wordTwo"
  $('#wordTwo').text(wordTwo);
};


//calls the API to get a new random ADJECTIVE
var getWord = function() {
  $.ajax({
    url : API_Endpoint_Word, 
    dataType : 'jsonp',
    success : function(response){
      console.log(response.word);
      //call the loadWord function to load the word into the DOM
      loadWord(response);

      //calls the getDef function to get the definition of wordOne from the API
      getDef(response.word);
    }

  });
};

//calls the API to get a new random NOUN
var getWordTwo = function() {
  $.ajax({
    url : API_Endpoint_Word_Two, 
    dataType : 'jsonp',
    success : function(response){
      console.log(response.word);
      //call the loadWord function to load the word into the DOM
      loadWordTwo(response);

      //calls the getDefTwo function to get the definition of wordTwo from the API
      getDefTwo(response.word);
    }
  });
};

//loads a random book cover from the array into the DOM
var loadCover = function(chosenCover){

  $('#bookCover').html(chosenCover);

};

//gets a random book cover from the array
var getCover = function(){
  
  var len = coverArray.length;

  //picks a random index number from the array
  var which = Math.round(Math.random()*(len-1));
  console.log(which);
    
  //stores the contents of the chosen slot in the array in a variable
  var chosenCover = coverArray[which];
  //log what the array returns
  console.log(coverArray[which]);
  //calls loadCover function with the parameter of which cover was chosen
  loadCover(chosenCover);

};

var init = function() {
  console.log('ready!!');

  
  //LOOK, MA! Some vanilla Javascript!
  var titleMeButton = document.getElementById('titleMe');

//event listener for clicking the "Title Me, Doll" button
  titleMeButton.addEventListener('click', function(e){
    e.preventDefault();
    //calls getWord function to get a new adjective from the API
    getWord();
    //calls getWordTwo function to get a new noun from the API
    getWordTwo();
  });

  var coverMeButton = document.getElementById('coverMe');

//event listener for clicking the "Go Under Cover" button
  coverMeButton.addEventListener('click', function(e){
    e.preventDefault();
    //calls getCover function to load a different cover image
    getCover();
    console.log(getCover);
  });

};

window.onload = init();

